CREATE TABLE "admin" (
  "ad_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ad_name" varchar NOT NULL,
  "ad_email" varchar UNIQUE NOT NULL,
  "ad_password" varchar NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "teacher" (
  "te_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "te_name" varchar NOT NULL,
  "te_surname" varchar NOT NULL,
  "te_email" varchar UNIQUE NOT NULL,
  "te_password" varchar NOT NULL,
  "te_state" int(2) NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "course" (
  "co_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "te_id" integer NOT NULL,
  "co_name" varchar NOT NULL,
  "co_state" bool NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "student" (
  "st_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "st_name" varchar NOT NULL,
  "st_surname" varchar NOT NULL,
  "co_id" integer NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "attendance" (
  "at_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "at_description" varchar NOT NULL,
  "at_date" timestamp NOT NULL
);

CREATE TABLE "stu_atten" (
  "stu_at_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "st_id" integer NOT NULL,
  "at_id" integer NOT NULL,
  "stu_at_isPresent" bool NOT NULL
);

ALTER TABLE "course" ADD FOREIGN KEY ("te_id") REFERENCES "teacher" ("te_id");

ALTER TABLE "student" ADD FOREIGN KEY ("co_id") REFERENCES "course" ("co_id");

ALTER TABLE "stu_atten" ADD FOREIGN KEY ("st_id") REFERENCES "student" ("st_id");

ALTER TABLE "stu_atten" ADD FOREIGN KEY ("at_id") REFERENCES "attendance" ("at_id");
