CREATE TABLE "admin" (
  "ad_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ad_name" varchar NOT NULL,
  "ad_email" varchar UNIQUE NOT NULL,
  "ad_password" varchar NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "teacher" (
  "te_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "te_name" varchar NOT NULL,
  "te_surname" varchar NOT NULL,
  "te_email" varchar UNIQUE NOT NULL,
  "te_password" varchar NOT NULL,
  "te_status" bool NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "course" (
  "co_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "te_id" integer NOT NULL,
  "co_name" varchar NOT NULL,
  "co_status" bool NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "student" (
  "st_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "te_id" integer NOT NULL,
  "st_name" varchar NOT NULL,
  "st_surname" varchar NOT NULL,
  "st_status" bool NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "course_student" (
  "cost_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "co_id" integer NOT NULL,
  "st_id" integer NOT NULL
);

CREATE TABLE "attendance" (
  "at_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "co_id" integer NOT NULL,
  "at_description" varchar,
  "at_date" timestamp NOT NULL
);

CREATE TABLE "attendance_student" (
  "at_st_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "at_id" integer NOT NULL,
  "st_id" integer NOT NULL,
  "at_st_isPresent" bool NOT NULL
);

CREATE TABLE "materia" (
  "ma_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "co_id" integer NOT NULL,
  "ma_name" varchar NOT NULL
);

CREATE TABLE "materia_student" (
  "mast_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_id" integer NOT NULL,
  "st_id" integer NOT NULL
);

CREATE TABLE "assignment" (
  "as_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_id" integer NOT NULL,
  "as_description" varchar NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "grade" (
  "gr_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "as_id" integer NOT NULL,
  "st_id" integer NOT NULL,
  "gr_quantity" float NOT NULL
);

ALTER TABLE "course" ADD FOREIGN KEY ("te_id") REFERENCES "teacher" ("te_id");

ALTER TABLE "course_student" ADD FOREIGN KEY ("co_id") REFERENCES "course" ("co_id");

ALTER TABLE "course_student" ADD FOREIGN KEY ("st_id") REFERENCES "student" ("st_id");

ALTER TABLE "student" ADD FOREIGN KEY ("te_id") REFERENCES "teacher" ("te_id");

ALTER TABLE "attendance" ADD FOREIGN KEY ("co_id") REFERENCES "course" ("co_id");

ALTER TABLE "attendance_student" ADD FOREIGN KEY ("at_id") REFERENCES "attendance" ("at_id");

ALTER TABLE "attendance_student" ADD FOREIGN KEY ("st_id") REFERENCES "student" ("st_id");

ALTER TABLE "materia" ADD FOREIGN KEY ("co_id") REFERENCES "course" ("co_id");

ALTER TABLE "materia_student" ADD FOREIGN KEY ("ma_id") REFERENCES "materia" ("ma_id");

ALTER TABLE "materia_student" ADD FOREIGN KEY ("st_id") REFERENCES "student" ("st_id");

ALTER TABLE "assignment" ADD FOREIGN KEY ("ma_id") REFERENCES "materia" ("ma_id");

ALTER TABLE "grade" ADD FOREIGN KEY ("as_id") REFERENCES "assignment" ("as_id");

ALTER TABLE "grade" ADD FOREIGN KEY ("st_id") REFERENCES "student" ("st_id");


-- -----------------------------INSERTS
